{% set version = '2.4-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geomap
  version: {{ version|replace("-", "_") }}

source:
  fn: GEOmap_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/GEOmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GEOmap/GEOmap_{{ version }}.tar.gz
  sha256: 101f177135514572d2aba44633dae4a870019340cf8570662a9571c61dd86272

build:
  merge_build_host: True  # [win]
  number: 1001
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mba
    - r-rpmg
    - r-fields
    - r-splancs
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mba
    - r-rpmg
    - r-fields
    - r-splancs

test:
  commands:
    - $R -e "library('GEOmap')"           # [not win]
    - "\"%R%\" -e \"library('GEOmap')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GEOmap
  license: GPL (>= 2)
  summary: Set of routines for making Map Projections (forward and inverse), Topographic Maps,
    Perspective plots, Geological Maps, geological map symbols, geological databases,
    interactive plotting and selection of focus regions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
