{% set version = "2.5-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geomap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GEOmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GEOmap/GEOmap_{{ version }}.tar.gz
  sha256: 82e5608eda7330632bc67aa662b649e7b7b3ccdfda6a18a19d2e3379e0db1093

build:
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mba
    - r-rpmg
    - r-fields
    - r-splancs
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mba
    - r-rpmg
    - r-fields
    - r-splancs

test:
  commands:
    - $R -e "library('GEOmap')"           # [not win]
    - "\"%R%\" -e \"library('GEOmap')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GEOmap
  license: GPL-2.0-or-later
  summary: Set of routines for making Map Projections (forward and inverse), Topographic Maps, Perspective plots, Geological Maps, geological map symbols, geological databases, interactive plotting and selection of focus regions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
